project:
  type: website
  output-dir: _site

format:
  revealjs:
    theme: default
    css: styles.css
    slide-level: 1
    slide-number: true
    controls: true
    progress: true
    mermaid:
      theme: neutral
    preview-links: auto
